name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Obbligatorio per Trusted Publishing (OIDC)
    environment:
      name: pypi
      url: https://pypi.org/p/moabile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tool
        run: python3 -m pip install --upgrade build

      - name: Build sdist and wheel
        run: python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
